AITA/urls.py
from django.urls import path

from . import views

app_name = 'AITA'

urlpatterns = [
    # ex: /AITA/
    path('', views.landing_page, name='landing'),
    path('intro/', views.intro, name='intro'),
    path('post/', views.show_post, name='post'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('showcase/nimAI/', include('nimAI.urls', namespace='nimAI')),
    path('showcase/AITA/', include('AITA.urls', namespace='AITA')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.welcome, name='welcome'),
]

nimAI/urls.py
from django.urls import path

from . import views

app_name = 'nimAI'

urlpatterns = [
    path('', views.index, name='index'),
    path('reset/', views.reset, name='reset'),
    path('train/', views.show_training_options, name='train'),
    path('play/', views.train_and_show_board, name='nim'),
    path('ai_move/', views.send_ai_move, name='ai_move'),
]

AITA/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=500)
    body = models.TextField()
    is_asshole = models.IntegerField()

    class Meta:
       db_table = 'posts'

nimAI/models.py
from django.db import models

# Create your models here.

AITA/views.py
from django.shortcuts import render
from .models import Post

import random


def landing_page(request):
    return render(request, 'AITA/landing.html')


def intro(request):
    return render(request, 'AITA/intro.html')


def show_post(request):
    post = Post.objects.all()
    random_post = random.choice(post)
    context = {
        'post': random_post
    }
    return render(request, 'AITA/detail.html', context=context)

main/views.py
from django.shortcuts import render


def welcome(request):
    return render(request, 'main/index.html')

nimAI/views.py
import time

from django.shortcuts import render
from django.http import JsonResponse

from .AI.nim_gameplay import (train_and_initialize,
                              update_game_state,
                              ai_lost,
                              ai_move,
                              declare_human_winner,
                              update_high_score,
                              reset_board)

INITIAL_BOARD = [1, 3, 5, 7]


def index(request):
    """
    Render landing page with the options to
    - expand and read the rules
    - select training options
    """
    request.session["high_score"] = request.session.get("high_score", 0)
    context = {"high_score": request.session["high_score"]}

    request.session.modified = True
    return render(request, "nimAI/index.html", context)


def reset(request):
    """
    Reset the board without training the AI agent again.
    """
    reset_board(request.session, board=INITIAL_BOARD.copy())

    context = {
        "new_board": request.session["current_board"],
        "new_board_len_range": range(len(request.session["current_board"])),
        "row_ranges": [range(row) for row in request.session["current_board"]],
        "winner": request.session["winner"],
        "high_score": request.session["high_score"]
    }

    request.session.modified = True
    return render(request, "nimAI/nim.html", context)


def show_training_options(request):
    """
    Render training page,
    allowing user to select the amount of AI training rounds
    """
    request.session["high_score"] = request.session.get("high_score", 0)
    context = {"high_score": request.session["high_score"]}

    request.session.modified = True
    return render(request, "nimAI/nim_train.html", context)


def train_and_show_board(request):
    """
    Train AI agent
    and render game-playing page with initialized board
    """
    # Training with n_train rounds is requested
    if request.method == "POST":
        n_train = int(request.POST["n_train"])

    # BE validation to avoid malicious post requests
    # (n_train cannot be set to > 300 by using FE functionality)
    if n_train > 300:
        exit()

    # The input slider is not linear.
    # For higher numbers, one slider unit increases n_train quicker.
    if n_train > 200:
        n_train = 1000 + (n_train - 200) * 90
    elif n_train > 100:
        n_train = 100 + (n_train - 100) * 9

    request.session["n_train"] = n_train
    request.session["high_score"] = request.session.get("high_score", 0)

    train_and_initialize(request.session, n_train, board=INITIAL_BOARD.copy())
    time.sleep(2.9)

    context = {
        "new_board": request.session["current_board"],
        "new_board_len_range": range(len(request.session["current_board"])),
        "row_ranges": [range(row) for row in request.session["current_board"]],
        "winner": request.session["winner"],
        "high_score": request.session["high_score"]
    }

    request.session.modified = True
    return render(request, "nimAI/nim.html", context)


def send_ai_move(request):
    """
    Update board state representation.
    Request an AI move and send it back to client as JSON.
    Requests are managed via AJAX.
    """
    print("Board before player move:", request.session["current_board"])

    def get_player_move(session, request):
        pile = amount = None
        for i in range(len(session["current_board"])):
            # Form input will only be non-empty for the selected row
            if request.POST.getlist(f"row_{i}"):  # e.g., ["Clicked", "Clicked", "Clicked]
                pile = i
                amount = len(request.POST.getlist(f"row_{i}"))

        print("Player pile, amount:", pile, amount)
        return pile, amount

    # Player's move
    player_pile, player_amount = get_player_move(request.session, request)
    update_game_state(request.session, player_pile, player_amount)

    print("Board after player move:", request.session["current_board"])

    # AI's move
    ai_pile, ai_amount = ai_move(request.session)

    print("AI pile, amount:", ai_pile, ai_amount)
    update_game_state(request.session, ai_pile, ai_amount)

    print("Board after AI move:", request.session["current_board"])

    if ai_lost(request.session["current_board"]):
        print("ai lost")
        declare_human_winner(request.session)
        update_high_score(request.session)

    data = {
        "winner": request.session["winner"],
        "pile": ai_pile,
        "amount": ai_amount,
        "high_score": request.session["high_score"]
    }

    request.session.modified = True
    return JsonResponse(data)

AITA/templates/AITA/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'main/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'AITA/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'AITA/css/basic.css' %}">
    {% block css-imports %}{% endblock %}
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>

</head>
<body>
{% block content %}{% endblock %}

<div id="jokus-pokus">
    <a href="{% url 'main:welcome' %}">
        <img src="{% static 'nimAI/img/favicon.png' %}" alt="">
    </a>
</div>

</body>
</html>

AITA/templates/AITA/detail.html
{% extends 'AITA/base.html' %}

{% load static %}

{% block css-imports %}
    <link rel="stylesheet" href="{% static 'AITA/css/landing.css' %}">
    <link rel="stylesheet" href="{% static 'AITA/css/styles.css' %}">

{% endblock %}

{% block title %}AITA?{% endblock %}

{% block content %}
    <div class="container main-container">
        <div class="row main-row">

            <h2><strong>{{ post.title }}</strong></h2>


            <div id="content-1" class="box sketchy overflow-auto my-3 custom-scrollbar-css">
                <div class="post">
                    <p>{{ post.body|linebreaks|safe }}</p>
                </div>
                <p class="feedback-correct hidden-element"><strong>Correct!</strong></p>
                <p class="feedback-incorrect hidden-element"><strong>Incorrect!</strong></p>
            </div>

            <div class="col-5">
                <button type="button" id="asshole" class="btn btn-dark mt-3 float-sm-end">Asshole</button>
            </div>

            <div class="col-2 text-center">
                <a href="{% url 'AITA:post' %}">
                    <button id="next"><h1 class="mt-3">&rightarrowtail;</h1></button>
                </a>
            </div>


            <div class="col-5 text-left">
                <button type="button" id="no-asshole" class="btn-light mt-3">Not an Asshole</button>
            </div>

        </div>

    </div>


    <script>
        $('#asshole').click(function () {
            if ({{ post.is_asshole }} == 1
        )
            {
                $('body').css('animation', 'change-color-correct 1s forwards');
                $('.post').addClass('hidden-element');
                $('.feedback-correct').removeClass('hidden-element');
            }
        else
            {
                $('body').css('animation', 'change-color-incorrect 1s forwards');
                $('.post').addClass('hidden-element');
                $('.feedback-incorrect').removeClass('hidden-element');
            }
            ;
            $('#asshole').css('visibility', 'hidden');
            $('#no-asshole').css('visibility', 'hidden');
            $('#next').css('visibility', 'visible');
        });

        $('#no-asshole').click(function () {
            if ({{ post.is_asshole }} == 0
        )
            {
                $('body').css('animation', 'change-color-correct 1s forwards');
                $('.post').addClass('hidden-element');
                $('.feedback-correct').removeClass('hidden-element');
            }
        else
            {
                $('body').css('animation', 'change-color-incorrect 1s forwards');
                $('.post').addClass('hidden-element');
                $('.feedback-incorrect').removeClass('hidden-element');
            }
            ;
            $('#asshole').css('visibility', 'hidden');
            $('#no-asshole').css('visibility', 'hidden');
            $('#next').css('visibility', 'visible');
        });

        $(function () {
            /* Rounded Dots Dark */
            $("#content-1").mCustomScrollbar({
                theme: "rounded-dots-dark"
            });
        });
    </script>
{% endblock %}

AITA/templates/AITA/intro.html
{% extends 'AITA/base.html' %}
{% load static %}

{% block title %}Welcome{% endblock %}

{% block css-imports %}
    <link rel="stylesheet" href="{% static 'AITA/css/landing.css' %}">
    <link rel="stylesheet" href="{% static 'AITA/css/intro.css' %}">
{% endblock %}

{% block content %}
    <!-- The video -->
    <video autoplay muted loop id="browsingVideo">
        <source src="{% static 'AITA/media/dark_browsing.mp4' %}" type="video/mp4">
    </video>

    <!-- Optional: some overlay text to describe the video -->
    <div class="content">
        <p class="mt-5">In the famous subreddit
            <a href="https://www.reddit.com/r/AmItheAsshole/" target="_blank" class="highlight">
                <span>r/AmItheAsshole</span>
            </a>,
            users describe a situation<br>in which they believe
            they <strong>might have acted</strong> like an asshole.</p>
        <p>Then, the community returns a verdict.</p>
        <p>Can you guess what the majority thinks?</p>
        <p>
            <a href="{% url 'AITA:post' %}">
                <button id="next"><h1>&rightarrowtail;</h1></button>
            </a>
        </p>
    </div>
{% endblock %}

AITA/templates/AITA/landing.html
{% extends 'AITA/base.html' %}
{% load static %}

{% block css-imports %}
    <link rel="stylesheet" href="{% static 'AITA/css/landing.css' %}">
{% endblock %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="title">

        <h1>Am I the<br/>Asshole?</h1>

        <a href="{% url 'AITA:intro' %}"><button id="next"><h1>&rightarrowtail;</h1></button></a>

    </div>


    <script>
        $( '#next' ).mouseover(function() {
            $( 'body' ).css( 'animation', 'change-color-to 1s forwards')
        })

        $( '#next' ).mouseout(function() {
            $( 'body' ).css( 'animation', 'change-color-back 1s forwards')
        })

    </script>
{% endblock %}

nimAI/templates/nimAI/index.html
{% extends "nimAI/layout.html" %}
{% load static %}

{% block body %}

    <!-- Option to extend rules -->
    <div class="content__rules">
        <div class="info">
            <button id="rules__btn" class="" onclick="showRules()">
                <i class="fa fa-info icon-info-sign" aria-hidden="true"></i>
                <span class="extra-info">
                CHECK OUT RULES
            </span>
            </button>
        </div>
    </div>

    <!-- Welcome message -->
    <div class="content__container index__container">
        <div class="screen-alert">
            <div id="message">
                <div class="" id="welcome" role="alert">
                    Welcome to the game!
                </div>
            </div>
        </div>
        <h3 id="index__slogan" class="mt-4 mb-3 explanations">Can you learn faster than the AI?</h3>
        <h4 id="index__slogan" class="mt-4 mb-3 explanations">Check out the rules on the top left info button!</h4>

        <a href="{% url 'nimAI:train' %}">
            <button id="challenge-accepted" class="content__btn">Challenge accepted!</button>
        </a>
    </div>

    <!-- Explanation of rules -->
    <div id="rules__text" class="content__container index__container mt-3 mb-5" style="display:none;">
        <div>
            <p class="explanations">Nim is a game for 2 players. In this version, there are 4 rows with
                different amounts of coins:</p>
            <img class="my-5 explanations__img" src="{% static 'nimAI/img/initial_board.PNG' %}" alt="Initial Nim board"
                 style="width:50%">
            <p class="explanations">Until the game is over, you and the AI take turns in removing
                coins from the board. In each turn, you have to pick a row. From that row, you can remove
                as many coins as you want - <strong>but at least 1!</strong></p>
            <p class="explanations">Whoever takes the last coin on the board <strong>loses</strong> the game. Hence,
                your goal is to force the AI to take the last coin.</p>
            <img class="my-5 explanations__img" src="{% static 'nimAI/img/board_end.PNG' %}" alt="Initial Nim board"
                 style="width:30%">
            <p class="explanations">In this state of the board, the winning move would be to remove both coins from
                the second row. Then, all the AI can do is take the last remaining coin and lose.</p>
            <a href="{% url 'nimAI:train' %}">
                <button class="content__btn">Let's go!</button>
            </a>
        </div>
    </div>

{% endblock %}

nimAI/templates/nimAI/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta id="winner" data-winnerName="{{ winner }}">

    <link href="{% static 'main/img/favicon.png' %}" rel="icon">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'nimAI/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Iceland&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>nimAI</title>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
</head>

<body>

<div class="wrapper">
    <main class="content ">

        <!-- Display high score -->
        <div id="high-score">Your high score: {{ high_score }}</div>
        <a href="{% url 'nimAI:index' %}">
            <div class="logo">&#60; nimAI &#62;</div>
        </a>

        {% block body %}
            <!-- Body is specified in templates -->
        {% endblock %}

        <!-- Authors -->
        <div id="credits">
            <div>
                <a href="https://www.linkedin.com/in/ibayova/" target="_blank">
                    <i class="fa fa-linkedin-square"></i>
                </a>
                Irina (Frontend, Design)
            </div>
            <div class="ml-5">
                <a href="https://www.linkedin.com/in/jakob-schmitt-048179196/" target="_blank">
                    <i class="fa fa-linkedin-square"></i>
                </a>
                Jakob (Machine Learning, Backend, Frontend)
            </div>
        </div>

        <div id="jokus-pokus">
            <a href="{% url 'main:welcome' %}">
                <img src="{% static 'nimAI/img/favicon.png' %}" alt="">
            </a>
        </div>

    </main>
    <div id="particles-js"></div>

    {% block scripts %}
    {% endblock %}

</div>
<script src="{% static 'nimAI/js/particles.js' %}"></script>
<script src="{% static 'nimAI/js/main.js' %}"></script>
</body>
</html>

nimAI/templates/nimAI/nim.html
{% extends "nimAI/layout.html" %}
{% load static %}
{% load index %}

{% block body %}

    <!-- Visual game tracking (coin board) -->
    <div class="form-wrapper">
        <form action="{% url 'nimAI:ai_move' %}"
              id="makeMove" method="POST" class="make-move-form">
            <ul id="board" class="mb-3 mx-3 board-list">
                {% for i in new_board_len_range %}
                    <div class="row board-list__row" id="row_{{ i }}">
                        {% for j in row_ranges|index:i %}
                            <li class="bounce-in-top board-list__item">
                                <input class="board-list__check" type="checkbox" id="coin{{ i }}{{ j }}"
                                       name="row_{{ i }}"
                                       value="Clicked"/>
                                <label for="coin{{ i }}{{ j }}"><img class="board-list__img "
                                                                     src="https://www.bitgild.com/wp-content/uploads/2020/01/50g-china-panda-gold-proof-2020-1-2.png"/></label>
                            </li>
                        {% endfor %}
                    </div>
                {% endfor %}
            </ul>
            {% csrf_token %}
        </form>
    </div>

    <!-- Message after user loses -->
    <div id="losing-animation" class="result content__container mb-5" hidden>
        <p class="explanations__opaque">Don't you wonder how the AI became smart enough to beat you...?</p>
        <p class="explanations__opaque">Check out my Medium article on Q-learning!</p>
        <div class="controls">
            <a href="https://medium.com/@jakob.schmitt/who-learns-faster-you-or-my-ai-681e442416b0" target="_blank">
                <button class="content__btn">Read article</button>
            </a>
        </div>
    </div>

    <!-- Message after user wins -->
    <div id="winning-animation" class="result content__container mb-5" hidden>
        <p class="explanations__opaque">Not bad... Now make the AI smarter and try again!</p>
        <p class="explanations__opaque">What's the highest number you can beat?</p>
        <div class="controls">
            <a href="{% url 'nimAI:train' %}">
                <button class="content__btn">Make it harder!</button>
            </a>
        </div>
    </div>

    <!-- Game control elements for human player -->
    <div class="ai-ops content__container mb-5">
        <div class="screen-alert">
            <div id="message">
                <div class="" role="alert">
                    Select coins and submit move!
                </div>
            </div>
        </div>
        <div class="controls">
            <a href="{% url 'nimAI:train' %}">
                <button type="submit" class="controls-btn mr-3">Change Level</button>
            </a>
            <button form="makeMove" type="submit" id="submit-btn" class="content__btn" disabled>Submit move</button>
            <form action="{% url 'nimAI:reset' %}" id="reset" method="GET" class="">
                <button type="submit" class="controls-btn ml-3">Reset game</button>
                {% csrf_token %}
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}

    <script>
        $(".board-list__item").click(function () {
            let remainingCheckedCoins = $("#board input:checked").length;
            if (remainingCheckedCoins == 0) {
                // No coins have been selected
                $("#submit-btn").prop("disabled", true);
            } else {
                // At least one coin is currently selected
                $("#submit-btn").prop("disabled", false);
            }

        });

        $("#makeMove").submit(function (event) {

            event.preventDefault(); // avoid to execute the actual submit of the form.

            // Disable submit button
            $("#submit-btn").prop("disabled", true);

            // Player Move --> Let the selected coins disappear
            $("#board li:has(input:checked)").addClass("hidden");
            $(".board-list__item").each(function () {
                $(this).parent().css("opacity", "1");
                $(this).find("input").attr("disabled", false);
            });
            let remainingCoins = $("#board li:not(.hidden)").length;

            if (remainingCoins != 0) {
                // Human has not lost --> AI move is required.
                $("#message").html("<div class='' role='alert'>AI is analyzing the board...</div>");

                const form = $(this);
                const url = form.attr("action");

                $.ajax({
                    url: url,
                    method: "POST",
                    async: false,
                    data: form.serialize(), // serializes the form's elements
                    dataType: "json",
                    success: function (ai_response) {
                        // Uncheck the now hidden coins
                        $("#board li.hidden input").prop("checked", false);

                        $("#board li").each(function () {
                            if ($(this).css("visibility") === "hidden") {
                                $(this).find("label").addClass('row__placeholder');
                                $(this).animate({opacity: 0.0}, 2000);
                            }
                        });
                        window.setTimeout(function () {
                            // Implement AI move
                            let ai_pile = ai_response["pile"];
                            let ai_amount = ai_response["amount"];
                            let rowName = "row_" + ai_pile.toString();
                            for (i = 0; i < ai_amount; i++) {
                                $("#board li:not('.hidden'):has(input[name=" + rowName + "])").last().addClass("hidden");
                            }

                            if (ai_response["winner"] === "Human") {
                                // Make winning animation visible
                                $("#submit-btn").prop("disabled", true);

                                let new_high_score = ai_response["high_score"];

                                window.setTimeout(function () {
                                    $("#message").html("<div class='' role='alert'>Congrats, you won!</div>");
                                    $("#board").attr("hidden", true);
                                    $("#winning-animation").attr("hidden", false);
                                    $("#high-score").html("Your high score: " + new_high_score.toString())
                                }, 500);
                            } else {
                                $("#message").html("<div class='' role='alert'>AI made a move. Your turn!</div>");
                            }
                        }, 1500);
                    }
                });
            } else {
                // Make losing animation visible
                $("#submit-btn").prop("disabled", true);
                window.setTimeout(function () {
                    $("#message").html("<div class='' role='alert'>Oops... You lost!</div>");
                    $("#board").attr("hidden", true);
                    $("#losing-animation").attr("hidden", false);
                }, 500);
            }
        });
    </script>

{% endblock %}

nimAI/templates/nimAI/nim_train.html
{% extends "nimAI/layout.html" %}
{% load static %}

{% block body %}

    <div class="content__container">

        <!-- Initial message -->
        <div class="screen-alert">
            <div id="message">
                <div id="message-display" class="" role="alert">
                    Let the AI learn the game!
                </div>
            </div>
        </div>

        <!-- Training control -->
        <form method="POST" id="train" action="{% url 'nimAI:nim' %}">

            <div class="mt-4 explanations">
                <p>To become a Nim master, the AI needs to
                    practice by playing against itself.</p>
                <p><strong>You</strong> decide how many rounds the agent is allowed to practice.</p>
            </div>
            <div class="d-flex justify-content-center flex-column">
                <div id="value-display" class="value">1</div>
                <input name="n_train" type="range" class="mt-4 train-slider" min="1" max="300" required
                       value="1">
                <div class="level">EASY PEASY</div>
            </div>
            {% csrf_token %}
        </form>

    </div>
    <div class="content-controllers d-flex justify-content-center">
        <button type="submit" form="train" class="content__btn" id="train-btn" onclick="showPreloader()">Start
            Training!
        </button>

    </div>

    <!-- Training buffer animation -->
    <div class="preload">
        <img class="brain" src="{% static 'nimAI/img/brain.png' %}">
        <span class="preload__text ml-3">Training</span>
        <span class="dots preload__text">...</span>
    </div>

{% endblock %}